udp_client:
	gcc udp_client.c -o udp_client.out
udp_server:
	gcc udp_server.c -o udp_server.out
tcp_client:
	gcc tcp_client.c -o tcp_client.out
tcp_server:
	gcc tcp_server.c -o tcp_server.out
tcp_server_fork:
	gcc tcp_server_fork.c -o tcp_server_fork.out
getaddrinfo_demo:
	gcc getaddrinfo_demo.c -o getaddrinfo_demo.out
clean:
	rm *.out
