no_sync:
	gcc -pthread no_sync.c -o no_sync.out
mutex:
	gcc -pthread mutex.c -o mutex.out
condvar:
	gcc -pthread condvar.c -o condvar.out
atomic:
	gcc -pthread atomic.c -o atomic.out
clean:
	rm *.out
