no_sync.out: no_sync.c
	gcc -pthread no_sync.c -o no_sync.out
mutex.out: mutex.c
	gcc -pthread mutex.c -o mutex.out
condvar.out: condvar.c
	gcc -pthread condvar.c -o condvar.out
atomic.out: atomic.c
	gcc -pthread atomic.c -o atomic.out
clean:
	rm *.out
