no_sync.out:
	gcc -pthread no_sync.c -o no_sync.out
mutex.out:
	gcc -pthread mutex.c -o mutex.out
condvar.out:
	gcc -pthread condvar.c -o condvar.out
atomic.out:
	gcc -pthread atomic.c -o atomic.out
clean:
	rm *.out
