udp_client.out: udp_client.c
	gcc udp_client.c -o udp_client.out
udp_server.out:
	gcc udp_server.c -o udp_server.out
tcp_client.out:
	gcc tcp_client.c -o tcp_client.out
tcp_server.out:
	gcc tcp_server.c -o tcp_server.out
tcp_server_fork.out:
	gcc tcp_server_fork.c -o tcp_server_fork.out
getaddrinfo_demo.out:
	gcc getaddrinfo_demo.c -o getaddrinfo_demo.out
clean:
	rm *.out
