fork_hello.out: fork_hello.c
	gcc fork_hello.c -o fork_hello.out
mmap_shared.out: mmap_shared.c
	gcc mmap_shared.c -o mmap_shared.out
simple_shell.out: simple_shell.c
	gcc simple_shell.c -o simple_shell.out
parallel_sum.out: parallel_sum.c
	gcc parallel_sum.c -o parallel_sum.out
clean:
	rm *.out
