read_buff.out: read_buff.c
	gcc read_buff.c -o read_buff.out
lseek_demo.out: lseek_demo.c
	gcc lseek_demo.c -o lseek_demo.out
pread_demo.out: pread_demo.c
	gcc pread_demo.c -o pread_demo.out
writev_demo.out: writev_demo.c
	gcc writev_demo.c -o writev_demo.out
count_filetypes.out: count_filetypes.c
	gcc count_filetypes.c -o count_filetypes.out
list_dir.out: list_dir.c
	gcc list_dir.c -o list_dir.out
time.out: time.c
	gcc time.c -o time.out
clean:
	rm *.out
