read_buff.out:
	gcc read_buff.c -o read_buff.out
lseek_demo.out:
	gcc lseek_demo.c -o lseek_demo.out
pread_demo.out:
	gcc pread_demo.c -o pread_demo.out
writev_demo.out:
	gcc writev_demo.c -o writev_demo.out
count_filetypes.out:
	gcc count_filetypes.c -o count_filetypes.out
list_dir.out:
	gcc list_dir.c -o list_dir.out
clean:
	rm *.out
