mmap_demo.out: mmap_demo.c
	gcc mmap_demo.c -o mmap_demo.out
proc_mem_demo.out: proc_mem_demo.c
	gcc proc_mem_demo.c -o proc_mem_demo.out
sections.out: sections.c
	gcc sections.c -o sections.out
clean:
	rm *.out
