freopen.out: freopen.c
	gcc freopen.c -o freopen.out
redirect.out: redirect.c
	gcc redirect.c -o redirect.out
pipe.out: pipe.c
	gcc pipe.c -o pipe.out
fifo.out: fifo.c
	gcc fifo.c -o fifo.out
sigaction_demo.out: sigaction_demo.c
	gcc sigaction_demo.c -o sigaction_demo.out
sigprocmask_demo.out: sigprocmask_demo.c
	gcc sigprocmask_demo.c -o sigprocmask_demo.out
sigsuspend_demo.out: sigsuspend_demo.c
	gcc sigsuspend_demo.c -o sigsuspend_demo.out
signalfd_demo.out: signalfd_demo.c
	gcc signalfd_demo.c -o signalfd_demo.out
sigqueue_demo.out: sigqueue_demo.c
	gcc sigqueue_demo.c -o sigqueue_demo.out
alarm_demo.out: alarm_demo.c
	gcc alarm_demo.c -o alarm_demo.out
sigwaitinfo_demo.out: sigwaitinfo_demo.c
	gcc sigwaitinfo_demo.c -o sigwaitinfo_demo.out
timerfd_demo.out: timerfd_demo.c
	gcc timerfd_demo.c -o timerfd_demo.out
clean:
	rm *.out

