sigaction_demo:
	gcc sigaction_demo.c -o sigaction_demo.out
sigprocmask_demo:
	gcc sigprocmask_demo.c -o sigprocmask_demo.out
sigsuspend_demo:
	gcc sigsuspend_demo.c -o sigsuspend_demo.out
signalfd_demo:
	gcc signalfd_demo.c -o signalfd_demo.out
sigqueue_demo:
	gcc sigqueue_demo.c -o sigqueue_demo.out
alarm_demo:
	gcc alarm_demo.c -o alarm_demo.out
sigwaitinfo_demo:
	gcc sigwaitinfo_demo.c -o sigwaitinfo_demo.out
timerfd_demo:
	gcc timerfd_demo.c -o timerfd_demo.out
clean:
	rm *.out