mmap_demo:
	gcc mmap_demo.c -o mmap_demo.out
caches_demo:
	gcc caches_demo.c -o caches_demo.out
proc_mem_demo:
	gcc proc_mem_demo.c -o proc_mem_demo.out
sections:
	gcc sections.c -o sections.out
clean:
	rm *.out
